version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: stock-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: stockmanager  
      MYSQL_USER: manager          
      MYSQL_PASSWORD: manager   
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
